// Code generated by "stringer -type=Type -output=trigger_type_string.go"; DO NOT EDIT.

package trigger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[System-1]
	_ = x[Verification-32]
	_ = x[Application-64]
}

const (
	_Type_name_0 = "System"
	_Type_name_1 = "Verification"
	_Type_name_2 = "Application"
)

func (i Type) String() string {
	switch {
	case i == 1:
		return _Type_name_0
	case i == 32:
		return _Type_name_1
	case i == 64:
		return _Type_name_2
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
