package smartcontract_test

import (
	"testing"

	nftd "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/nft-d"
	nftd_dynamic "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/nft-d/dynamic_hash"
	nftnd "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/nft-nd"
	nftnd_dynamic "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/nft-nd/dynamic_hash"
	notifications "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/notifications/rpcbindings"
	notifications_extended "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/notifications/rpcbindings/extended"
	notifications_guessed "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/notifications/rpcbindings/guessed"
	royalty "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/royalty/rpcbindings"
	royalty_dynamic "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/royalty/rpcbindings/dynamic_hash"
	structs "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/structs/rpcbindings"
	structs_dynamic "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/structs/rpcbindings/dynamic_hash"
	types "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/types/rpcbindings"
	types_dynamic "github.com/nspcc-dev/neo-go/cli/smartcontract/testdata/rpcbindings/types/rpcbindings/dynamic_hash"
)

// TestAssistedRPCBindings_Compileability ensures that RPC bindings generated by the users of
// rewriteExpectedOutputs are buildable.
func TestAssistedRPCBindings_Compilability(t *testing.T) {
	var (
		_ = nftnd_dynamic.Contract{}
		_ = nftnd.Contract{}
		_ = nftd.Contract{}
		_ = nftd_dynamic.Contract{}
		_ = notifications.Contract{}
		_ = notifications_extended.Contract{}
		_ = notifications_guessed.Contract{}
		_ = royalty.Contract{}
		_ = royalty_dynamic.Contract{}
		_ = structs.ContractReader{}
		_ = structs_dynamic.ContractReader{}
		_ = types.ContractReader{}
		_ = types_dynamic.ContractReader{}
	)
}
