// Code generated by "stringer -type=AttrType -linecomment"; DO NOT EDIT.

package transaction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HighPriority-1]
	_ = x[OracleResponseT-17]
	_ = x[NotValidBeforeT-32]
	_ = x[ConflictsT-33]
	_ = x[NotaryAssistedT-34]
}

const (
	_AttrType_name_0 = "HighPriority"
	_AttrType_name_1 = "OracleResponse"
	_AttrType_name_2 = "NotValidBeforeConflictsNotaryAssisted"
)

var (
	_AttrType_index_2 = [...]uint8{0, 14, 23, 37}
)

func (i AttrType) String() string {
	switch {
	case i == 1:
		return _AttrType_name_0
	case i == 17:
		return _AttrType_name_1
	case 32 <= i && i <= 34:
		i -= 32
		return _AttrType_name_2[_AttrType_index_2[i]:_AttrType_index_2[i+1]]
	default:
		return "AttrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
