// Code generated by "stringer -type=AttrUsage"; DO NOT EDIT.

package transaction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DescriptionURL-129]
}

const _AttrUsage_name = "DescriptionURL"

var _AttrUsage_index = [...]uint8{0, 14}

func (i AttrUsage) String() string {
	i -= 129
	if i >= AttrUsage(len(_AttrUsage_index)-1) {
		return "AttrUsage(" + strconv.FormatInt(int64(i+129), 10) + ")"
	}
	return _AttrUsage_name[_AttrUsage_index[i]:_AttrUsage_index[i+1]]
}
