// Code generated by "stringer -type AttrType"; DO NOT EDIT.

package transaction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HighPriority-1]
}

const _AttrType_name = "HighPriority"

var _AttrType_index = [...]uint8{0, 12}

func (i AttrType) String() string {
	i -= 1
	if i >= AttrType(len(_AttrType_index)-1) {
		return "AttrType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AttrType_name[_AttrType_index[i]:_AttrType_index[i+1]]
}
