// Code generated by "stringer -type=WitnessAction -linecomment"; DO NOT EDIT.

package transaction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WitnessDeny-0]
	_ = x[WitnessAllow-1]
}

const _WitnessAction_name = "DenyAllow"

var _WitnessAction_index = [...]uint8{0, 4, 9}

func (i WitnessAction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WitnessAction_index)-1 {
		return "WitnessAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WitnessAction_name[_WitnessAction_index[idx]:_WitnessAction_index[idx+1]]
}
