// Code generated by "stringer -type=StorageSyncMode"; DO NOT EDIT.

package statesync

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MPTBased-0]
	_ = x[ContractStorageBased-1]
}

const _StorageSyncMode_name = "MPTBasedContractStorageBased"

var _StorageSyncMode_index = [...]uint8{0, 8, 28}

func (i StorageSyncMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StorageSyncMode_index)-1 {
		return "StorageSyncMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageSyncMode_name[_StorageSyncMode_index[idx]:_StorageSyncMode_index[idx+1]]
}
