// Code generated by "stringer -type=handShakeStage"; DO NOT EDIT.

package network

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nothingDone-0]
	_ = x[versionSent-1]
	_ = x[versionReceived-2]
	_ = x[verAckSent-3]
	_ = x[verAckReceived-4]
}

const _handShakeStage_name = "nothingDoneversionSentversionReceivedverAckSentverAckReceived"

var _handShakeStage_index = [...]uint8{0, 11, 22, 37, 47, 61}

func (i handShakeStage) String() string {
	if i >= handShakeStage(len(_handShakeStage_index)-1) {
		return "handShakeStage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _handShakeStage_name[_handShakeStage_index[i]:_handShakeStage_index[i+1]]
}
