// Code generated by "stringer -type=RelayReason -output=relay_reason_string.go"; DO NOT EDIT.

package network

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RelaySucceed-0]
	_ = x[RelayAlreadyExists-1]
	_ = x[RelayOutOfMemory-2]
	_ = x[RelayUnableToVerify-3]
	_ = x[RelayInvalid-4]
	_ = x[RelayPolicyFail-5]
	_ = x[RelayUnknown-6]
}

const _RelayReason_name = "RelaySucceedRelayAlreadyExistsRelayOutOfMemoryRelayUnableToVerifyRelayInvalidRelayPolicyFailRelayUnknown"

var _RelayReason_index = [...]uint8{0, 12, 30, 46, 65, 77, 92, 104}

func (i RelayReason) String() string {
	if i >= RelayReason(len(_RelayReason_index)-1) {
		return "RelayReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RelayReason_name[_RelayReason_index[i]:_RelayReason_index[i+1]]
}
