// Code generated by "stringer -type=Role"; DO NOT EDIT.

package noderoles

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateValidator-4]
	_ = x[Oracle-8]
	_ = x[NeoFSAlphabet-16]
	_ = x[P2PNotary-32]
	_ = x[last-64]
}

const (
	_Role_name_0 = "StateValidator"
	_Role_name_1 = "Oracle"
	_Role_name_2 = "NeoFSAlphabet"
	_Role_name_3 = "P2PNotary"
	_Role_name_4 = "last"
)

func (i Role) String() string {
	switch {
	case i == 4:
		return _Role_name_0
	case i == 8:
		return _Role_name_1
	case i == 16:
		return _Role_name_2
	case i == 32:
		return _Role_name_3
	case i == 64:
		return _Role_name_4
	default:
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
