package compiler

var syscalls = map[string]map[string]string{
	"account": {
		"GetBalance":    "Neo.Account.GetBalance",
		"GetScriptHash": "Neo.Account.GetScriptHash",
		"GetVotes":      "Neo.Account.GetVotes",
		"IsStandard":    "Neo.Account.IsStandard",
	},
	"attribute": {
		"GetUsage": "Neo.Attribute.GetUsage",
		"GetData":  "Neo.Attribute.GetData",
	},
	"crypto": {
		"ECDsaVerify": "Neo.Crypto.ECDsaVerify",
	},
	"enumerator": {
		"Concat": "Neo.Enumerator.Concat",
		"Create": "Neo.Enumerator.Create",
		"Next":   "Neo.Enumerator.Next",
		"Value":  "Neo.Enumerator.Value",
	},
	"storage": {
		"ConvertContextToReadOnly": "Neo.StorageContext.AsReadOnly",
		"Delete":                   "Neo.Storage.Delete",
		"Find":                     "Neo.Storage.Find",
		"Get":                      "Neo.Storage.Get",
		"GetContext":               "Neo.Storage.GetContext",
		"GetReadOnlyContext":       "Neo.Storage.GetReadOnlyContext",
		"Put":                      "Neo.Storage.Put",
	},
	"runtime": {
		"GetTrigger":   "Neo.Runtime.GetTrigger",
		"CheckWitness": "Neo.Runtime.CheckWitness",
		"Notify":       "Neo.Runtime.Notify",
		"Log":          "Neo.Runtime.Log",
		"GetTime":      "Neo.Runtime.GetTime",
		"Serialize":    "Neo.Runtime.Serialize",
		"Deserialize":  "Neo.Runtime.Deserialize",
	},
	"blockchain": {
		"GetAccount":           "Neo.Blockchain.GetAccount",
		"GetAsset":             "Neo.Blockchain.GetAsset",
		"GetBlock":             "Neo.Blockchain.GetBlock",
		"GetContract":          "Neo.Blockchain.GetContract",
		"GetHeader":            "Neo.Blockchain.GetHeader",
		"GetHeight":            "Neo.Blockchain.GetHeight",
		"GetTransaction":       "Neo.Blockchain.GetTransaction",
		"GetTransactionHeight": "Neo.Blockchain.GetTransactionHeight",
		"GetValidators":        "Neo.Blockchain.GetValidators",
	},
	"header": {
		"GetIndex":         "Neo.Header.GetIndex",
		"GetHash":          "Neo.Header.GetHash",
		"GetPrevHash":      "Neo.Header.GetPrevHash",
		"GetTimestamp":     "Neo.Header.GetTimestamp",
		"GetVersion":       "Neo.Header.GetVersion",
		"GetMerkleRoot":    "Neo.Header.GetMerkleRoot",
		"GetConsensusData": "Neo.Header.GetConsensusData",
		"GetNextConsensus": "Neo.Header.GetNextConsensus",
	},
	"block": {
		"GetTransactionCount": "Neo.Block.GetTransactionCount",
		"GetTransactions":     "Neo.Block.GetTransactions",
		"GetTransaction":      "Neo.Block.GetTransaction",
	},
	"transaction": {
		"GetAttributes": "Neo.Transaction.GetAttributes",
		"GetHash":       "Neo.Transaction.GetHash",
		"GetInputs":     "Neo.Transaction.GetInputs",
		"GetOutputs":    "Neo.Transaction.GetOutputs",
		"GetReferences": "Neo.Transaction.GetReferences",
		"GetScript":     "Neo.InvocationTransaction.GetScript",
		"GetType":       "Neo.Transaction.GetType",
		"GetWitnesses":  "Neo.Transaction.GetWitnesses",
	},
	"asset": {
		"Create":       "Neo.Asset.Create",
		"GetAdmin":     "Neo.Asset.GetAdmin",
		"GetAmount":    "Neo.Asset.GetAmount",
		"GetAssetID":   "Neo.Asset.GetAssetID",
		"GetAssetType": "Neo.Asset.GetAssetType",
		"GetAvailable": "Neo.Asset.GetAvailable",
		"GetIssuer":    "Neo.Asset.GetIssuer",
		"GetOwner":     "Neo.Asset.GetOwner",
		"GetPrecision": "Neo.Asset.GetPrecision",
		"Renew":        "Neo.Asset.Renew",
	},
	"contract": {
		"GetScript":         "Neo.Contract.GetScript",
		"IsPayable":         "Neo.Contract.IsPayable",
		"Create":            "Neo.Contract.Create",
		"Destroy":           "Neo.Contract.Destroy",
		"Migrate":           "Neo.Contract.Migrate",
		"GetStorageContext": "Neo.Contract.GetStorageContext",
	},
	"input": {
		"GetHash":  "Neo.Input.GetHash",
		"GetIndex": "Neo.Input.GetIndex",
	},
	"output": {
		"GetAssetID":    "Neo.Output.GetAssetID",
		"GetValue":      "Neo.Output.GetValue",
		"GetScriptHash": "Neo.Output.GetScriptHash",
	},
	"engine": {
		"GetScriptContainer":     "System.ExecutionEngine.GetScriptContainer",
		"GetCallingScriptHash":   "System.ExecutionEngine.GetCallingScriptHash",
		"GetEntryScriptHash":     "System.ExecutionEngine.GetEntryScriptHash",
		"GetExecutingScriptHash": "System.ExecutionEngine.GetExecutingScriptHash",
	},
	"iterator": {
		"Concat": "Neo.Iterator.Concat",
		"Create": "Neo.Iterator.Create",
		"Key":    "Neo.Iterator.Key",
		"Keys":   "Neo.Iterator.Keys",
		"Next":   "Neo.Iterator.Next",
		"Value":  "Neo.Iterator.Value",
		"Values": "Neo.Iterator.Values",
	},
	"witness": {
		"GetVerificationScript": "Neo.Witness.GetVerificationScript",
	},
}
