// Code generated by neo-go contract generate-rpcwrapper --manifest <file.json> --out <file.go> [--hash <hash>] [--config <config>]; DO NOT EDIT.

// Package structs contains RPC wrappers for Types contract.
package structs

import (
	"crypto/elliptic"
	"errors"
	"fmt"
	"github.com/nspcc-dev/neo-go/pkg/core/state"
	"github.com/nspcc-dev/neo-go/pkg/crypto/keys"
	"github.com/nspcc-dev/neo-go/pkg/neorpc/result"
	"github.com/nspcc-dev/neo-go/pkg/rpcclient/ledger"
	"github.com/nspcc-dev/neo-go/pkg/rpcclient/unwrap"
	"github.com/nspcc-dev/neo-go/pkg/smartcontract"
	"github.com/nspcc-dev/neo-go/pkg/util"
	"github.com/nspcc-dev/neo-go/pkg/vm/stackitem"
	"math/big"
	"unicode/utf8"
)

// StructsInternal is a contract-specific structs.Internal type used by its methods.
type StructsInternal struct {
	Bool            bool
	Int             *big.Int
	Bytes           []byte
	String          string
	H160            util.Uint160
	H256            util.Uint256
	PK              *keys.PublicKey
	PubKey          *keys.PublicKey
	Sign            []byte
	ArrOfBytes      [][]byte
	ArrOfH160       []util.Uint160
	Map             map[*big.Int]keys.PublicKeys
	Struct          *StructsInternal
	UnexportedField *big.Int
}

// Invoker is used by ContractReader to call various safe methods.
type Invoker interface {
	Call(contract util.Uint160, operation string, params ...any) (*result.Invoke, error)
}

// ContractReader implements safe contract methods.
type ContractReader struct {
	invoker Invoker
	hash    util.Uint160
}

// NewReader creates an instance of ContractReader using provided contract hash and the given Invoker.
func NewReader(invoker Invoker, hash util.Uint160) *ContractReader {
	return &ContractReader{invoker, hash}
}

// Block invokes `block` method of contract.
func (c *ContractReader) Block(b *ledger.Block) (*ledger.Block, error) {
	return unwrap.Convertible[ledger.Block](unwrap.Item(c.invoker.Call(c.hash, "block", b)))
}

// Contract invokes `contract` method of contract.
func (c *ContractReader) Contract(mc *state.Contract) (*state.Contract, error) {
	return unwrap.Convertible[state.Contract](unwrap.Item(c.invoker.Call(c.hash, "contract", mc)))
}

// Struct invokes `struct` method of contract.
func (c *ContractReader) Struct(s *StructsInternal) (*StructsInternal, error) {
	return itemToStructsInternal(unwrap.Item(c.invoker.Call(c.hash, "struct", s)))
}

// Transaction invokes `transaction` method of contract.
func (c *ContractReader) Transaction(t *ledger.Transaction) (*ledger.Transaction, error) {
	return unwrap.Convertible[ledger.Transaction](unwrap.Item(c.invoker.Call(c.hash, "transaction", t)))
}

// itemToStructsInternal converts stack item into *StructsInternal.
// NULL item is returned as nil pointer without error.
func itemToStructsInternal(item stackitem.Item, err error) (*StructsInternal, error) {
	if err != nil {
		return nil, err
	}
	_, null := item.(stackitem.Null)
	if null {
		return nil, nil
	}
	var res = new(StructsInternal)
	err = res.FromStackItem(item)
	return res, err
}

// Ensure *StructsInternal is a proper [stackitem.Convertible].
var _ = stackitem.Convertible(&StructsInternal{})

// Ensure *StructsInternal is a proper [smartcontract.Convertible].
var _ = smartcontract.Convertible(&StructsInternal{})

// FromStackItem retrieves fields of StructsInternal from the given
// [stackitem.Item] or returns an error if it's not possible to do to so.
// It implements [stackitem.Convertible] interface.
func (res *StructsInternal) FromStackItem(item stackitem.Item) error {
	arr, ok := item.Value().([]stackitem.Item)
	if !ok {
		return errors.New("not an array")
	}
	if len(arr) != 14 {
		return errors.New("wrong number of structure elements")
	}

	var (
		index = -1
		err   error
	)
	index++
	res.Bool, err = arr[index].TryBool()
	if err != nil {
		return fmt.Errorf("field Bool: %w", err)
	}

	index++
	res.Int, err = arr[index].TryInteger()
	if err != nil {
		return fmt.Errorf("field Int: %w", err)
	}

	index++
	res.Bytes, err = arr[index].TryBytes()
	if err != nil {
		return fmt.Errorf("field Bytes: %w", err)
	}

	index++
	res.String, err = func(item stackitem.Item) (string, error) {
		b, err := item.TryBytes()
		if err != nil {
			return "", err
		}
		if !utf8.Valid(b) {
			return "", errors.New("not a UTF-8 string")
		}
		return string(b), nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field String: %w", err)
	}

	index++
	res.H160, err = func(item stackitem.Item) (util.Uint160, error) {
		b, err := item.TryBytes()
		if err != nil {
			return util.Uint160{}, err
		}
		u, err := util.Uint160DecodeBytesBE(b)
		if err != nil {
			return util.Uint160{}, err
		}
		return u, nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field H160: %w", err)
	}

	index++
	res.H256, err = func(item stackitem.Item) (util.Uint256, error) {
		b, err := item.TryBytes()
		if err != nil {
			return util.Uint256{}, err
		}
		u, err := util.Uint256DecodeBytesBE(b)
		if err != nil {
			return util.Uint256{}, err
		}
		return u, nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field H256: %w", err)
	}

	index++
	res.PK, err = func(item stackitem.Item) (*keys.PublicKey, error) {
		b, err := item.TryBytes()
		if err != nil {
			return nil, err
		}
		k, err := keys.NewPublicKeyFromBytes(b, elliptic.P256())
		if err != nil {
			return nil, err
		}
		return k, nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field PK: %w", err)
	}

	index++
	res.PubKey, err = func(item stackitem.Item) (*keys.PublicKey, error) {
		b, err := item.TryBytes()
		if err != nil {
			return nil, err
		}
		k, err := keys.NewPublicKeyFromBytes(b, elliptic.P256())
		if err != nil {
			return nil, err
		}
		return k, nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field PubKey: %w", err)
	}

	index++
	res.Sign, err = arr[index].TryBytes()
	if err != nil {
		return fmt.Errorf("field Sign: %w", err)
	}

	index++
	res.ArrOfBytes, err = func(item stackitem.Item) ([][]byte, error) {
		arr, ok := item.Value().([]stackitem.Item)
		if !ok {
			return nil, errors.New("not an array")
		}
		res := make([][]byte, len(arr))
		for i := range res {
			res[i], err = arr[i].TryBytes()
			if err != nil {
				return nil, fmt.Errorf("item %d: %w", i, err)
			}
		}
		return res, nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field ArrOfBytes: %w", err)
	}

	index++
	res.ArrOfH160, err = func(item stackitem.Item) ([]util.Uint160, error) {
		arr, ok := item.Value().([]stackitem.Item)
		if !ok {
			return nil, errors.New("not an array")
		}
		res := make([]util.Uint160, len(arr))
		for i := range res {
			res[i], err = func(item stackitem.Item) (util.Uint160, error) {
				b, err := item.TryBytes()
				if err != nil {
					return util.Uint160{}, err
				}
				u, err := util.Uint160DecodeBytesBE(b)
				if err != nil {
					return util.Uint160{}, err
				}
				return u, nil
			}(arr[i])
			if err != nil {
				return nil, fmt.Errorf("item %d: %w", i, err)
			}
		}
		return res, nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field ArrOfH160: %w", err)
	}

	index++
	res.Map, err = func(item stackitem.Item) (map[*big.Int]keys.PublicKeys, error) {
		m, ok := item.Value().([]stackitem.MapElement)
		if !ok {
			return nil, fmt.Errorf("%s is not a map", item.Type().String())
		}
		res := make(map[*big.Int]keys.PublicKeys)
		for i := range m {
			k, err := m[i].Key.TryInteger()
			if err != nil {
				return nil, fmt.Errorf("key %d: %w", i, err)
			}
			v, err := func(item stackitem.Item) (keys.PublicKeys, error) {
				arr, ok := item.Value().([]stackitem.Item)
				if !ok {
					return nil, errors.New("not an array")
				}
				res := make(keys.PublicKeys, len(arr))
				for i := range res {
					res[i], err = func(item stackitem.Item) (*keys.PublicKey, error) {
						b, err := item.TryBytes()
						if err != nil {
							return nil, err
						}
						k, err := keys.NewPublicKeyFromBytes(b, elliptic.P256())
						if err != nil {
							return nil, err
						}
						return k, nil
					}(arr[i])
					if err != nil {
						return nil, fmt.Errorf("item %d: %w", i, err)
					}
				}
				return res, nil
			}(m[i].Value)
			if err != nil {
				return nil, fmt.Errorf("value %d: %w", i, err)
			}
			res[k] = v
		}
		return res, nil
	}(arr[index])
	if err != nil {
		return fmt.Errorf("field Map: %w", err)
	}

	index++
	res.Struct, err = itemToStructsInternal(arr[index], nil)
	if err != nil {
		return fmt.Errorf("field Struct: %w", err)
	}

	index++
	res.UnexportedField, err = arr[index].TryInteger()
	if err != nil {
		return fmt.Errorf("field UnexportedField: %w", err)
	}

	return nil
}

// ToStackItem creates [stackitem.Item] representing StructsInternal.
// It implements [stackitem.Convertible] interface.
func (res *StructsInternal) ToStackItem() (stackitem.Item, error) {
	if res == nil {
		return stackitem.Null{}, nil
	}

	var (
		err   error
		itm   stackitem.Item
		items = make([]stackitem.Item, 0, 14)
	)
	itm, err = stackitem.NewBool(res.Bool), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field Bool: %w", err)
	}
	items = append(items, itm)

	itm, err = (*stackitem.BigInteger)(res.Int), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field Int: %w", err)
	}
	items = append(items, itm)

	itm, err = stackitem.NewByteArray(res.Bytes), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field Bytes: %w", err)
	}
	items = append(items, itm)

	itm, err = stackitem.NewByteArray([]byte(res.String)), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field String: %w", err)
	}
	items = append(items, itm)

	itm, err = stackitem.NewByteArray(res.H160.BytesBE()), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field H160: %w", err)
	}
	items = append(items, itm)

	itm, err = stackitem.NewByteArray(res.H256.BytesBE()), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field H256: %w", err)
	}
	items = append(items, itm)

	itm, err = stackitem.NewByteArray(res.PK.Bytes()), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field PK: %w", err)
	}
	items = append(items, itm)

	itm, err = stackitem.NewByteArray(res.PubKey.Bytes()), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field PubKey: %w", err)
	}
	items = append(items, itm)

	itm, err = stackitem.NewByteArray(res.Sign), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field Sign: %w", err)
	}
	items = append(items, itm)

	itm, err = func(in [][]byte) (stackitem.Item, error) {
		if in == nil {
			return stackitem.Null{}, nil
		}

		var items = make([]stackitem.Item, 0, len(in))
		for i, v := range in {
			itm, err := stackitem.NewByteArray(v), error(nil)
			if err != nil {
				return nil, fmt.Errorf("item %d: %w", i, err)
			}
			items = append(items, itm)
		}
		return stackitem.NewArray(items), nil
	}(res.ArrOfBytes)
	if err != nil {
		return nil, fmt.Errorf("field ArrOfBytes: %w", err)
	}
	items = append(items, itm)

	itm, err = func(in []util.Uint160) (stackitem.Item, error) {
		if in == nil {
			return stackitem.Null{}, nil
		}

		var items = make([]stackitem.Item, 0, len(in))
		for i, v := range in {
			itm, err := stackitem.NewByteArray(v.BytesBE()), error(nil)
			if err != nil {
				return nil, fmt.Errorf("item %d: %w", i, err)
			}
			items = append(items, itm)
		}
		return stackitem.NewArray(items), nil
	}(res.ArrOfH160)
	if err != nil {
		return nil, fmt.Errorf("field ArrOfH160: %w", err)
	}
	items = append(items, itm)

	itm, err = func(in map[*big.Int]keys.PublicKeys) (stackitem.Item, error) {
		if in == nil {
			return stackitem.Null{}, nil
		}

		var m = stackitem.NewMap()
		for k, v := range in {
			iKey, err := (*stackitem.BigInteger)(k), error(nil)
			if err != nil {
				return nil, fmt.Errorf("key %v: %w", k, err)
			}
			iVal, err := func(in keys.PublicKeys) (stackitem.Item, error) {
				if in == nil {
					return stackitem.Null{}, nil
				}

				var items = make([]stackitem.Item, 0, len(in))
				for i, v := range in {
					itm, err := stackitem.NewByteArray(v.Bytes()), error(nil)
					if err != nil {
						return nil, fmt.Errorf("item %d: %w", i, err)
					}
					items = append(items, itm)
				}
				return stackitem.NewArray(items), nil
			}(v)
			if err != nil {
				return nil, fmt.Errorf("key %v, wrong value: %w", k, err)
			}
			m.Add(iKey, iVal)
		}
		return m, nil
	}(res.Map)
	if err != nil {
		return nil, fmt.Errorf("field Map: %w", err)
	}
	items = append(items, itm)

	itm, err = res.Struct.ToStackItem()
	if err != nil {
		return nil, fmt.Errorf("field Struct: %w", err)
	}
	items = append(items, itm)

	itm, err = (*stackitem.BigInteger)(res.UnexportedField), error(nil)
	if err != nil {
		return nil, fmt.Errorf("field UnexportedField: %w", err)
	}
	items = append(items, itm)

	return stackitem.NewStruct(items), nil
}

// ToSCParameter creates [smartcontract.Parameter] representing StructsInternal.
// It implements [smartcontract.Convertible] interface so that StructsInternal
// could be used with invokers.
func (res *StructsInternal) ToSCParameter() (smartcontract.Parameter, error) {
	if res == nil {
		return smartcontract.Parameter{Type: smartcontract.AnyType}, nil
	}

	var (
		err  error
		prm  smartcontract.Parameter
		prms = make([]smartcontract.Parameter, 0, 14)
	)
	prm, err = smartcontract.NewParameterFromValue(res.Bool)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field Bool: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.Int)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field Int: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.Bytes)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field Bytes: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.String)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field String: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.H160)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field H160: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.H256)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field H256: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.PK)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field PK: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.PubKey)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field PubKey: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.Sign)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field Sign: %w", err)
	}
	prms = append(prms, prm)

	prm, err = func(in [][]byte) (smartcontract.Parameter, error) {
		if in == nil {
			return smartcontract.Parameter{Type: smartcontract.AnyType}, nil
		}

		var prms = make([]smartcontract.Parameter, 0, len(in))
		for i, v := range in {
			prm, err := smartcontract.NewParameterFromValue(v)
			if err != nil {
				return smartcontract.Parameter{}, fmt.Errorf("item %d: %w", i, err)
			}
			prms = append(prms, prm)
		}
		return smartcontract.Parameter{Type: smartcontract.ArrayType, Value: prms}, nil
	}(res.ArrOfBytes)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field ArrOfBytes: %w", err)
	}
	prms = append(prms, prm)

	prm, err = func(in []util.Uint160) (smartcontract.Parameter, error) {
		if in == nil {
			return smartcontract.Parameter{Type: smartcontract.AnyType}, nil
		}

		var prms = make([]smartcontract.Parameter, 0, len(in))
		for i, v := range in {
			prm, err := smartcontract.NewParameterFromValue(v)
			if err != nil {
				return smartcontract.Parameter{}, fmt.Errorf("item %d: %w", i, err)
			}
			prms = append(prms, prm)
		}
		return smartcontract.Parameter{Type: smartcontract.ArrayType, Value: prms}, nil
	}(res.ArrOfH160)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field ArrOfH160: %w", err)
	}
	prms = append(prms, prm)

	prm, err = func(in map[*big.Int]keys.PublicKeys) (smartcontract.Parameter, error) {
		if in == nil {
			return smartcontract.Parameter{Type: smartcontract.AnyType}, nil
		}

		var prms = make([]smartcontract.ParameterPair, 0, len(in))
		for k, v := range in {
			iKey, err := smartcontract.NewParameterFromValue(k)
			if err != nil {
				return smartcontract.Parameter{}, fmt.Errorf("key %v: %w", k, err)
			}
			iVal, err := func(in keys.PublicKeys) (smartcontract.Parameter, error) {
				if in == nil {
					return smartcontract.Parameter{Type: smartcontract.AnyType}, nil
				}

				var prms = make([]smartcontract.Parameter, 0, len(in))
				for i, v := range in {
					prm, err := smartcontract.NewParameterFromValue(v)
					if err != nil {
						return smartcontract.Parameter{}, fmt.Errorf("item %d: %w", i, err)
					}
					prms = append(prms, prm)
				}
				return smartcontract.Parameter{Type: smartcontract.ArrayType, Value: prms}, nil
			}(v)
			if err != nil {
				return smartcontract.Parameter{}, fmt.Errorf("key %v, wrong value: %w", k, err)
			}
			prms = append(prms, smartcontract.ParameterPair{Key: iKey, Value: iVal})
		}
		return smartcontract.Parameter{Type: smartcontract.MapType, Value: prms}, nil
	}(res.Map)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field Map: %w", err)
	}
	prms = append(prms, prm)

	prm, err = res.Struct.ToSCParameter()
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field Struct: %w", err)
	}
	prms = append(prms, prm)

	prm, err = smartcontract.NewParameterFromValue(res.UnexportedField)
	if err != nil {
		return smartcontract.Parameter{}, fmt.Errorf("field UnexportedField: %w", err)
	}
	prms = append(prms, prm)

	return smartcontract.Parameter{Type: smartcontract.ArrayType, Value: prms}, nil
}
