// Code generated by neo-go contract generate-rpcwrapper --manifest <file.json> --out <file.go> [--hash <hash>] [--config <config>]; DO NOT EDIT.

// Package native contains RPC wrappers for Native contract.
package native

import (
	"errors"
	"fmt"
	"github.com/nspcc-dev/neo-go/pkg/core/state"
	"github.com/nspcc-dev/neo-go/pkg/core/transaction"
	"github.com/nspcc-dev/neo-go/pkg/neorpc/result"
	"github.com/nspcc-dev/neo-go/pkg/rpcclient/ledger"
	"github.com/nspcc-dev/neo-go/pkg/rpcclient/unwrap"
	"github.com/nspcc-dev/neo-go/pkg/util"
	"github.com/nspcc-dev/neo-go/pkg/vm/stackitem"
)

// Hash contains contract hash.
var Hash = util.Uint160{0x33, 0x22, 0x11, 0x0, 0xff, 0xee, 0xdd, 0xcc, 0xbb, 0xaa, 0x99, 0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x0}

// Invoker is used by ContractReader to call various safe methods.
type Invoker interface {
	Call(contract util.Uint160, operation string, params ...any) (*result.Invoke, error)
}

// ContractReader implements safe contract methods.
type ContractReader struct {
	invoker Invoker
	hash    util.Uint160
}

// NewReader creates an instance of ContractReader using Hash and the given Invoker.
func NewReader(invoker Invoker) *ContractReader {
	var hash = Hash
	return &ContractReader{invoker, hash}
}

// GetAccount invokes `getAccount` method of contract.
func (c *ContractReader) GetAccount(a *state.NEOBalance) (*state.NEOBalance, error) {
	return unwrap.Convertible[state.NEOBalance](unwrap.Item(c.invoker.Call(c.hash, "getAccount", a)))
}

// GetBlock invokes `getBlock` method of contract.
func (c *ContractReader) GetBlock(b *ledger.Block) (*ledger.Block, error) {
	return unwrap.Convertible[ledger.Block](unwrap.Item(c.invoker.Call(c.hash, "getBlock", b)))
}

// GetContract invokes `getContract` method of contract.
func (c *ContractReader) GetContract(mc *state.Contract) (*state.Contract, error) {
	return unwrap.Convertible[state.Contract](unwrap.Item(c.invoker.Call(c.hash, "getContract", mc)))
}

// GetSigners invokes `getSigners` method of contract.
func (c *ContractReader) GetSigners(s []*transaction.Signer) ([]*transaction.Signer, error) {
	return func(item stackitem.Item, err error) ([]*transaction.Signer, error) {
		if err != nil {
			return nil, err
		}
		return func(item stackitem.Item) ([]*transaction.Signer, error) {
			arr, ok := item.Value().([]stackitem.Item)
			if !ok {
				return nil, errors.New("not an array")
			}
			res := make([]*transaction.Signer, len(arr))
			for i := range res {
				res[i], err = unwrap.Convertible[transaction.Signer](arr[i], nil)
				if err != nil {
					return nil, fmt.Errorf("item %d: %w", i, err)
				}
			}
			return res, nil
		}(item)
	}(unwrap.Item(c.invoker.Call(c.hash, "getSigners", s)))
}

// GetWhitelist invokes `getWhitelist` method of contract.
func (c *ContractReader) GetWhitelist(w *state.WhitelistFeeContract) (*state.WhitelistFeeContract, error) {
	return unwrap.Convertible[state.WhitelistFeeContract](unwrap.Item(c.invoker.Call(c.hash, "getWhitelist", w)))
}
