// Code generated by "stringer -type=Hardfork -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HFAspidochelone-1]
}

const _Hardfork_name = "HF_Aspidochelone"

var _Hardfork_index = [...]uint8{0, 16}

func (i Hardfork) String() string {
	i -= 1
	if i >= Hardfork(len(_Hardfork_index)-1) {
		return "Hardfork(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Hardfork_name[_Hardfork_index[i]:_Hardfork_index[i+1]]
}
