// Code generated by "go generate go run gen.go"; DO NOT EDIT.

//go:generate go run gen.go

// package nativeids contains IDs of all native contracts.
package nativeids

// IDs of all native contracts.
const (
	// ContractManagement is an ID of native ContractManagement contract.
	ContractManagement int32 = -1
	// StdLib is an ID of native StdLib contract.
	StdLib int32 = -2
	// CryptoLib is an ID of native CryptoLib contract.
	CryptoLib int32 = -3
	// LedgerContract is an ID of native LedgerContract contract.
	LedgerContract int32 = -4
	// NeoToken is an ID of native NeoToken contract.
	NeoToken int32 = -5
	// GasToken is an ID of native GasToken contract.
	GasToken int32 = -6
	// PolicyContract is an ID of native PolicyContract contract.
	PolicyContract int32 = -7
	// RoleManagement is an ID of native RoleManagement contract.
	RoleManagement int32 = -8
	// OracleContract is an ID of native OracleContract contract.
	OracleContract int32 = -9
	// Notary is an ID of native Notary contract.
	Notary int32 = -10
	// Treasury is an ID of native Treasury contract.
	Treasury int32 = -11
)
