// Code generated by "stringer -type=OperationMode"; DO NOT EDIT.

package blockfetcher

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Blocks-0]
	_ = x[Headers-1]
}

const _OperationMode_name = "BlocksHeaders"

var _OperationMode_index = [...]uint8{0, 6, 13}

func (i OperationMode) String() string {
	if i >= OperationMode(len(_OperationMode_index)-1) {
		return "OperationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationMode_name[_OperationMode_index[i]:_OperationMode_index[i+1]]
}
